services:
  - type: web
    name: MT-evaluation-tool
    env: node
    plan: starter
    repo: https://github.com/OpenPecha/MT-evaluation-tool.git
    branch: main
    buildCommand: npm ci --production=false && npx prisma generate && npm run build && npm prune --production
    startCommand: npx prisma migrate deploy && npm run start
    envVars:
      - key: NODE_VERSION
        value: ~20.0.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: MT-evaluation-tool-pg
          property: connectionString

databases:
  - name: MT-evaluation-tool-pg
    plan: free